export const seedProducts = [
  {
    id: 'seed-nike-air-max',
    title: 'Nike Air Max Running Hombre',
    price: 89990,
    original_price: 119990,
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/nike-air-max',
    shipping: { free_shipping: true },
    official_store_name: 'Nike',
    sold_quantity: 1200,
  },
  {
    id: 'seed-nike-air-force-1',
    title: 'Nike Air Force 1 Urbanas',
    price: 74990,
    original_price: 99990,
    thumbnail: 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/nike-air-force-1',
    shipping: { free_shipping: true },
    official_store_name: 'Nike',
    sold_quantity: 980,
  },
  {
    id: 'seed-adidas-forum',
    title: 'Adidas Forum Low Unisex',
    price: 59990,
    original_price: 89990,
    thumbnail: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/adidas-forum',
    shipping: { free_shipping: true },
    official_store_name: 'Adidas',
    sold_quantity: 640,
  },
  {
    id: 'seed-puma-suede',
    title: 'Puma Suede Classic',
    price: 49990,
    original_price: 69990,
    thumbnail: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/puma-suede',
    shipping: { free_shipping: true },
    official_store_name: 'Puma',
    sold_quantity: 430,
  },
  {
    id: 'seed-nb-550',
    title: 'New Balance 550 Urbanas',
    price: 109990,
    original_price: 139990,
    thumbnail: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/new-balance-550',
    shipping: { free_shipping: true },
    official_store_name: 'New Balance',
    sold_quantity: 210,
  },
  {
    id: 'seed-ua-running',
    title: 'Under Armour Charged Running',
    price: 79990,
    original_price: 99990,
    thumbnail: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/under-armour-running',
    shipping: { free_shipping: false },
    official_store_name: 'Under Armour',
    sold_quantity: 175,
  },
  {
    id: 'seed-columbia-trekking',
    title: 'Columbia Peakfreak Trekking',
    price: 129990,
    original_price: 159990,
    thumbnail: 'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/columbia-trekking',
    shipping: { free_shipping: true },
    official_store_name: 'Columbia',
    sold_quantity: 90,
  },
  {
    id: 'seed-nike-futbol',
    title: 'Nike Mercurial Fútbol',
    price: 84990,
    original_price: null,
    thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/nike-mercurial',
    shipping: { free_shipping: true },
    official_store_name: 'Nike',
    sold_quantity: 300,
  },
  {
    id: 'seed-adidas-ropa',
    title: 'Adidas Conjunto Deportivo',
    price: 39990,
    original_price: 54990,
    thumbnail: 'https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/adidas-conjunto-deportivo',
    shipping: { free_shipping: true },
    official_store_name: 'Adidas',
    sold_quantity: 510,
  },
  {
    id: 'seed-puma-mochila',
    title: 'Puma Mochila Training',
    price: 24990,
    original_price: 34990,
    thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/puma-mochila',
    shipping: { free_shipping: false },
    official_store_name: 'Puma',
    sold_quantity: 260,
  },
  {
    id: 'seed-nb-running',
    title: 'New Balance Fresh Foam Running',
    price: 119990,
    original_price: 149990,
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/new-balance-fresh-foam',
    shipping: { free_shipping: true },
    official_store_name: 'New Balance',
    sold_quantity: 140,
  },
  {
    id: 'seed-columbia-chaqueta',
    title: 'Columbia Chaqueta Impermeable',
    price: 89990,
    original_price: 129990,
    thumbnail: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=800&q=80',
    permalink: 'https://listado.mercadolibre.cl/columbia-chaqueta',
    shipping: { free_shipping: true },
    official_store_name: 'Columbia',
    sold_quantity: 88,
  },
]
